// ── Recommended Skills ──
export const RECOMMENDED_SKILLS = [
  "Accounting",
  "Adobe Photoshop",
  "Agile Methodology",
  "API Development",
  "Budgeting",
  "Business Analysis",
  "Branding",
  "Bookkeeping",
  "Coding",
  "CRM Management",
  "Copywriting",
  "CAD",
  "Data Analysis",
  "Digital Marketing",
  "Database Management (SQL)",
  "Debugging",
  "Excel",
  "Email Marketing",
  "ERP Systems",
  "Editing",
  "Financial Modeling",
  "Front End Development",
  "Figma",
  "Forecasting",
  "Google Analytics",
  "Graphic Design",
  "Git/GitHub",
  "HTML/CSS",
  "HRIS (Human Resource information system)",
  "Hadoop",
  "Illustration",
  "iOS Development",
  "Inventory Management",
  "Java",
  "JSON Handling",
  "Jira",
  "Journalism Techniques",
  "Kubernetes",
  "Keyword Research",
  "Knowledge Management",
  "Linux",
  "Laravel",
  "Lead Generation",
  "Legal Drafting",
  "Microsoft Office Suite",
  "Market Research",
  "Motion Graphics",
  "MySQL",
  "Networking (IT)",
  "Negotiation Tools",
  "Node.js",
  "Outlook",
  "Onboarding Process",
  "Oracle DB",
  "Operations Management",
  "Python",
  "Project Management",
  "Photoshop",
  "Power BI",
  "QA Testing",
  "QuickBooks",
  "Quantitative Analysis",
  "React.js",
  "Risk Analysis",
  "Reporting Tools",
  "Research",
  "SEO",
  "Social Media Management",
  "SQL",
  "Software Testing",
  "Tableau",
  "Technical Writing",
  "Time Tracking Tools",
  "Troubleshooting",
  "UI/UX Design",
  "Usability Testing",
  "Unreal Engine",
  "Video Editing",
  "Visual Design",
  "VMware",
  "Web Development",
  "WordPress",
  "Wireframing",
  "XML",
  "Xamarin",
  "YouTube Channel Management",
  "YAML",
  "Zoho CRM",
  "Zendesk",
  "Zapier Automation",
  "Adaptability",
  "Attention to detail",
  "Collaboration",
  "Communication",
  "Critical Thinking",
  "Creativity",
  "Decision Making",
  "Emotional Intelligence",
  "Leadership",
  "Multitasking",
  "Negotiation",
  "Organization",
  "Problem Solving",
  "Teamwork",
  "Time Management",
  "Work Ethic",
  "Conflict Resolution",
  "Flexibility",
  "Self-motivation",
];
