// ── Recommended Interests ──
export const RECOMMENDED_INTERESTS = [
  // Health & Wellness
  "Yoga",
  "Meditation",
  "Fitness",
  "Weight Loss",
  "Healthy Eating",
  "Mental Health",
  "Mindfulness",
  "Home Workouts",
  "Holistic Healing",
  "Sleep Optimization",

  // Arts & Creativity
  "Painting",
  "Photography",
  "Digital Art",
  "Writing",
  "Crafts",
  "Sketching",
  "DIY Projects",
  "Pottery",
  "Graphic Design",
  "Calligraphy",

  // Gaming
  "PC Gaming",
  "Console Gaming",
  "Mobile Games",
  "Esports",
  "RPGs",
  "Strategy Games",
  "Game Development",
  "VR Gaming",
  "Retro Games",

  // Education & Learning
  "Online Courses",
  "Coding",
  "Language Learning",
  "Study Groups",
  "STEM",
  "Reading Groups",
  "Personal Development",
  "Career Coaching",
  "Study Abroad",
  "Skill Sharing",

  // Lifestyle & Hobbies
  "Gardening",
  "Home Decor",
  "Travel",
  "Fashion",
  "Beauty Tips",
  "Journaling",
  "Minimalism",
  "Pet Care",
  "Foodies",
  "Sustainable Living",

  // Career
  "Freelancing",
  "Networking",
  "Marketing",
  "Productivity",
  "Remote Work",
  "Leadership",
  "Resume Building",
  "UX/UI Design",

  // Startup & Entrepreneurship
  "Pitch Practice",
  "MVP Development",
  "Startup Funding",
  "Founders' Network",
  "Accelerator Programs",
  "Product-Market Fit",
  "Startup Law",
  "Investor Relations",
  "Growth Hacking",
  "Tech for Good",
  "Go To Market",
  "Co-working Space",
  "Grants",

  // Music
  "Bollywood",
  "Rock",
  "Hip-Hop",
  "Indie",
  "Live Shows",
  "DJing",
  "Music Production",
  "K-pop",
  "Bhangra",

  // Sports & Outdoors
  "Football",
  "Cricket",
  "Running",
  "Cycling",
  "Hiking",
  "Gym Workouts",
  "Adventure",
  "Scuba Diving",
  "Camping",
  "Hockey",
  "Pickel Ball",
  "Tennis",
  "Swimming",

  // Technology
  "AI & ML",
  "Cybersecurity",
  "Blockchain",
  "IOT",
  "Data Science",
  "Open Source",
  "Robotics",
  "Analytics",

  // Community & Causes
  "Volunteering",
  "Environmentalism",
  "LGBTQ+",
  "Mental Health Advocacy",
  "Animal Welfare",
  "Women's Empowerment",
  "Blood Donation",
  "Climate Action",
  "Local Events",
  "Fundraising",
  "NGO",
  "Not for Profit",

  // Books & Literature
  "Fiction",
  "Non-fiction",
  "Poetry",
  "Book Clubs",
  "Biographies",
  "Fantasy Novels",
  "Audiobooks",
  "Reading Challenges",
  "Self-help Books",
  "Mystery & Thrillers",

  // Food & Cooking
  "Baking",
  "Vegan Recipes",
  "Street Food",
  "Home Cooking",
  "International Cuisine",
  "Meal Prep",
  "Food Photography",
  "BBQ",
  "Desserts",
  "Healthy Snacks",

  // Travel & Exploration
  "Backpacking",
  "Solo Travel",
  "Weekend Getaways",
  "Road Trips",
  "Cultural Travel",
  "Travel Photography",
  "Luxury Travel",
  "Digital Nomads",
  "Heritage Sites",
  "Eco-Tourism",

  // Parenting & Family
  "New Moms",
  "Single Parents",
  "Parenting Tips",
  "Kids Activities",
  "Homeschooling",
  "Baby Care",
  "Teen Parenting",
  "Family Travel",
  "Special Needs Parenting",
  "Work-Life Balance",

  // Culture & Traditions
  "Local Cuisine",
  "Folklore",
  "Traditional Crafts",
  "Ethnic Fashion",
  "Religious Festivals",
  "Cultural Exchange",
  "Ancestry",
  "Indigenous Cultures",
  "Multilingualism",
  "Historical Landmarks",

  // Movies & TV Shows
  "Hollywood",
  "Netflix Originals",
  "TV Show Reviews",
  "Cinephiles",
  "Documentaries",
  "Classic Films",
  "Movie Trivia",
  "Fan Theories",
  "Short Films",

  // Social & Dating
  "Making Friends",
  "Online Dating",
  "Dating Advice",
  "Relationship Tips",
  "Icebreaker Games",
  "Breakup Support",
  "Love Languages",
  "Virtual Speed Dating",
  "Couples Goals",
  "Friendship Goals",

  // Philosophy & Psychology
  "Positive Psychology",
  "Stoicism",
  "Mindset Growth",
  "Cognitive Science",
  "Philosophy 101",
  "Self-Awareness",
  "Existentialism",
  "Behavioral Psychology",
  "Emotional Intelligence",
  "Critical Thinking",

  // Finance & Money
  "Budgeting",
  "Saving Hacks",
  "Crypto",
  "Stock Market",
  "Real Estate",
  "Financial Literacy",
  "Passive Income",
  "Retirement Planning",
  "Credit Score Tips",
  "Tax Planning",

  // News & Current Affairs
  "World Politics",
  "Breaking News",
  "Local News",
  "Climate Crisis",
  "Tech News",
  "Economic Trends",
  "Legal Reforms",
  "Health News",
  "Social Justice",
  "Media Literacy",

  // DIY & Home Improvement
  "Woodworking",
  "Interior Design",
  "Upcycling",
  "Tool Hacks",
  "Gardening Projects",
  "Smart Homes",
  "Home Renovation",
  "Painting Walls",
  "Furniture Makeover",
  "Tiny Homes",

  // Career Development
  "Job Hunting",
  "Resume Reviews",
  "Interview Prep",
  "LinkedIn Tips",
  "Workplace Skills",
  "Career Switching",
  "Public Speaking",
  "Personal Branding",
  "Promotions & Raises",

  // Science & Discovery
  "Astronomy",
  "Space Exploration",
  "Physics Fun",
  "Chemistry Experiments",
  "Scientific News",
  "Wildlife Research",
  "Environmental Science",
  "Oceanography",
  "Genetics",
  "Citizen Science",

  // Women Empowerment
  "Career for Women",
  "Health & Hygiene",
  "Safety & Rights",
  "Female Entrepreneurs",
  "Women in Tech",
  "Inspirational Women",
  "Motherhood & Career",
  "Women in Sports",
  "Body Positivity",
  "Gender Equality",

  // Pets & Animals
  "Dog Training",
  "Cat Lovers",
  "Pet Nutrition",
  "Exotic Pets",
  "Animal Rescue",
  "Pet Adoption",
  "Wildlife Enthusiasts",
  "Aquarium Setup",
  "Pet Accessories",
  "Animal Rights",

  // Spirituality & Faith
  "Mindful Living",
  "Daily Devotionals",
  "Prayers & Meditation",
  "Interfaith Dialogues",
  "Scriptures & Texts",
  "Spiritual Quotes",
  "Sacred Music",
  "Rituals & Traditions",
  "Fasting & Festivals",
  "Inner Peace",

  // Self-Improvement
  "Habit Building",
  "Confidence Boost",
  "Morning Routines",
  "Vision Boards",
  "Mindset Shifts",
  "Life Coaching",
  "Productivity Systems",
  "Goal Setting",

  // Performing Arts
  "Theatre Acting",
  "Stand-Up Comedy",
  "Improvisation",
  "Stage Design",
  "Dance Forms",
  "Monologue Practice",
  "Stage Fright Tips",
  "Spoken Word",
  "Musical Theatre",
  "Street Performances",

  // Brain Games & Puzzles
  "Crosswords",
  "Sudoku",
  "Logic Games",
  "Escape Rooms",
  "Trivia Nights",
  "Memory Challenges",
  "Brain Training",
  "Word Games",
  "Riddles",
  "Puzzle Solvers Group",

  // Digital Nomad Life
  "Co-working Spaces",
  "Visa-Free Travel",
  "Time Zone Hacks",
  "Remote Jobs",
  "Digital Tools",
  "Nomad Visas",
  "Travel Insurance",
  "Minimalist Packing",
  "Nomad Meetups",

  // Health Tech & Biohacking
  "Wearables",
  "Intermittent Fasting",
  "Sleep Tracking",
  "Nootropics",
  "Cold Showers",
  "Red Light Therapy",
  "Bloodwork Insights",
  "Longevity Hacks",
  "Keto & Biohacking",

  // Teachers & Educators
  "Lesson Planning",
  "EdTech Tools",
  "Online Teaching",
  "Classroom Management",
  "Inclusive Education",
  "Exam Prep",
  "Student Engagement",
  "Remote Learning",
  "Teacher Wellness",
  "Curriculum Design",

  // Law & Legal
  "Legal Advice",
  "Constitutional Law",
  "Contract Law",
  "Startups & IP",
  "Cyber Law",
  "Legal News",
  "Mock Trials",
  "Law Student Tips",
  "Case Studies",
  "Legal Awareness",

  // Technology (Extra)
  "Vibe Coding",
  "JavaScript",
  "Frontend Dev",
  "Backend Dev",
  "App Development",
  "APIs & SDKs",
  "Open Source Projects",
  "DevOps",
  "Code Review Sessions",

  // Students & Campus Life
  "College Admissions",
  "Exam Stress Tips",
  "Campus Events",
  "Scholarships",
  "Study Tips",
  "Student Clubs",
  "Graduation Prep",
  "Notes Sharing",
  "Final Year Projects",

  // Productivity & Systems
  "Bullet Journaling",
  "Pomodoro Technique",
  "Notion Templates",
  "Time Blocking",
  "Eisenhower Matrix",
  "Focus Groups",
  "Digital Decluttering",
  "GTD (Getting Things Done)",
  "Minimalist Planning",
  "Deep Work",

  // Languages & Linguistics
  "Language Exchange",
  "Grammar Help",
  "Accent Practice",
  "Polyglots",
  "Sign Language",
  "Word of the Day",
  "Translation Tips",
  "Dialect Discussions",
  "Slang & Idioms",
  "Language Quizzes",

  // Public Speaking & Debate
  "Speech Writing",
  "Debate Clubs",
  "Body Language",
  "Voice Training",
  "Impromptu Speaking",
  "Toastmasters",
  "Storytelling",
  "Elevator Pitches",
  "Panel Moderation",
  "Persuasive Speaking",
  "Overcoming Stage Fright",

  // Dance & Movement
  "Zumba",
  "Hip Hop",
  "Ballet",
  "Classical Dance",
  "Contemporary",
  "Street Dance",
  "Choreography",
  "Dance Fitness",
  "Cultural Dances",
  "Freestyle Battles",

  // Design & Aesthetics
  "UI/UX Design",
  "Typography",
  "Color Theory",
  "Design Portfolios",
  "Logo Design",
  "Behance Showcases",
  "Motion Graphics",
  "Design Feedback",
  "Prototyping Tools",
  "Minimal Design",

  // Podcasting & Audio
  "Podcast Creation",
  "Audio Editing",
  "Equipment Reviews",
  "Voiceovers",
  "Hosting Tips",
  "Interviewing Skills",
  "Podcast Promotion",
  "Niche Podcasting",
  "Sound Effects",
  "Monetization Strategies",

  // Space & Astronomy
  "Stargazing",
  "Planetary Science",
  "Space Tech",
  "Telescopes",
  "Astrophysics",
  "Black Holes",
  "Mars Colonization",
  "Moon Phases",

  // Baking & Desserts
  "Cake Decorating",
  "Sourdough Baking",
  "Cookies & Biscuits",
  "Pies & Tarts",
  "Baking Hacks",
  "Gluten-Free Treats",
  "Chocolate Lovers",
  "Cupcake Art",
  "Festive Baking",
  "Bread Making",

  // Innovation & Creativity
  "Idea Incubation",
  "Brainstorming",
  "Creative Thinking",
  "Design Sprints",
  "Disruption Trends",
  "Prototyping Ideas",
  "Concept Testing",
  "Creative Confidence",
  "Blue Ocean Thinking",
  "Innovation Labs",

  // Alternative Healing
  "Reiki",
  "Crystal Healing",
  "Sound Therapy",
  "Aromatherapy",
  "Chakra Balancing",
  "Herbal Remedies",
  "Energy Medicine",
  "Breathwork",
  "Ayurvedic Practices",
  "Emotional Freedom Technique (EFT)",

  // Shopping & Style
  "Streetwear",
  "Thrift Finds",
  "Capsule Wardrobes",
  "Style Guides",
  "Luxury Fashion",
  "Sneakerheads",
  "Fashion Deals",
  "Outfit of the Day (OOTD)",
  "Personal Styling",
  "Fashion Hauls",

  // Life Coaching & Mentorship
  "Vision Building",
  "Accountability Circles",
  "Mentorship Matching",
  "Coaching Techniques",
  "Life Purpose Discovery",
  "Leadership Growth",
  "Goal Mapping",
  "Coaching Tools",
  "Breakthrough Sessions",
  "Empowerment Tips",

  // Culinary Arts
  "Knife Skills",
  "Food Plating",
  "Global Cuisine",
  "Culinary School Tips",
  "Fermentation",
  "Food Styling",
  "Gourmet Cooking",
  "Sauces & Dressings",
  "Culinary Competitions",
  "Chef Life",

  // Adventure & Thrill
  "Skydiving",
  "Paragliding",
  "Bungee Jumping",
  "White Water Rafting",
  "Rock Climbing",
  "Zip Lining",
  "Cave Exploration",
  "Desert Safari",
  "Glacier Hiking",
  "Extreme Sports",

  // E-commerce & Dropshipping
  "Shopify Tips",
  "Product Research",
  "Store Design",
  "Payment Gateways",
  "Customer Service",
  "Logistics & Fulfillment",
  "AliExpress Sourcing",
  "Sales Funnels",
  "Print on Demand",
  "Marketplace Strategies",

  // Mind & Memory
  "Memory Techniques",
  "Brain Nutrition",
  "Focus Training",
  "Mind Mapping",
  "Neuroplasticity",
  "Speed Reading",
  "Brain Games",
  "Meditation for Clarity",
  "Learning Hacks",
  "Cognitive Boost",

  // Eco Living & Sustainability
  "Zero Waste",
  "Plastic Alternatives",
  "Urban Gardening",
  "Sustainable Fashion",
  "Upcycled Furniture",
  "Solar Energy",
  "Eco Cleaning",
  "Green Tech",
  "Climate Advocacy",
  "Conscious Consumerism",

  // Content Creation
  "Vlogging Tips",
  "YouTube Strategy",
  "Scriptwriting",
  "Short-form Videos",
  "Instagram Reels",
  "Editing Tools",
  "Monetization Tactics",
  "Camera Setup",
  "Storyboarding",
  "Influencer Marketing",
];
