// ── Recommended Industries ──
export const RECOMMENDED_INDUSTRIES = [
  "Advertising & Media",
  "Advisory & Consulting Services",
  "Aerospace & Defence",
  "Agribusiness & Farming",
  "Airlines & Airport Services",
  "Architecture & Interior Design",
  "Automotive",
  "Banking",
  "Beauty",
  "Chemicals",
  "Construction",
  "Consumer Internet",
  "Consumer Products",
  "Defence & Security",
  "Ecology & Environment",
  "Education & Research",
  "Entertainment",
  "Event Management",
  "Facilities Management",
  "Fashion & Apparel",
  "Financial Services",
  "Gaming",
  "Government",
  "Health & Wellness",
  "High Tech",
  "HORECA",
  "Household Services",
  "Incubation & Entrepreneurship",
  "Industrial Manufacturing",
  "Influencers, Creators & Celebrities",
  "Information Technology",
  "Insurance",
  "Internet, D2C & E-commerce",
  "Legal",
  "Life Sciences & Healthcare",
  "Media Production",
  "Mill Products",
  "Mining",
  "Not For Profit",
  "Oil, Gas & Energy",
  "Performing Arts, Museums & Culture",
  "Profesional Networks",
  "Professional Association",
  "Professional Services",
  "Publishing & Printing",
  "Real Estate",
  "Real Estate - Commercial",
  "Real Estate - Residential",
  "Retail",
  "Sports",
  "Social Media & Networking",
  "Telecommunications",
  "Think Tanks",
  "Tours & Travels",
  "Trading",
  "Transportation, Logistics & Distribution",
  "Utilities",
  "VC, Private Equity & Angel Networks",
  "Veterinary Services",
  "Volunteering",
  "Zoos & Bootanical Gardens",
];
