import {
  FileText,
  HelpCircle,
  BookOpen,
  Download,
  ScrollText,
  Info,
  MessageSquare,
  Users,
  UserCheck,
  Trophy,
  MapPin,
  Award,
  Building,
  Briefcase,
  CreditCard,
  Handshake,
  FileBarChart,
  Gift,
  Megaphone,
  Mail,
  Shield,
  Timer,
  Bell,
  Heart,
  BarChart3,
  Table,
  BarChart,
  Calendar,
  Clock,
  Route,
  Image,
  Video,
  Share2,
  Headphones,
  Code,
  GraduationCap,
  FlaskConical,
  Star,
  Map,
  Phone,
} from "lucide-react";
import { ModuleType } from "@/store/useWebsiteBuilderStore";

export const AVAILABLE_MODULES: {
  type: ModuleType;
  name: string;
  description: string;
  defaultLayout: string;
  icon: any;
  category: string;
}[] = [
  // Content & Text
  {
    type: "custom-content",
    name: "Custom Content",
    description:
      "Flexible content section with headings, text, images, or rich content.",
    defaultLayout: "details-list",
    icon: FileText,
    category: "Content & Text",
  },
  {
    type: "faq",
    name: "FAQ",
    description: "Frequently asked questions in an expandable list.",
    defaultLayout: "simple-accordion",
    icon: HelpCircle,
    category: "Content & Text",
  },
  {
    type: "blog",
    name: "Blog",
    description:
      "Articles, guides, and content in various formats and layouts.",
    defaultLayout: "standard-article",
    icon: BookOpen,
    category: "Content & Text",
  },
  {
    type: "resources",
    name: "Resources",
    description: "Downloads, guides, tools, and helpful content library.",
    defaultLayout: "resource-cards",
    icon: Download,
    category: "Content & Text",
  },
  {
    type: "guidelines",
    name: "Community Guidelines",
    description: "Display rules, code of conduct, and participation standards.",
    defaultLayout: "simple-list",
    icon: ScrollText,
    category: "Content & Text",
  },
  {
    type: "callout",
    name: "Callout Box",
    description: "Short highlighted message or announcement.",
    defaultLayout: "info-box",
    icon: Info,
    category: "Content & Text",
  },
  {
    type: "ceo-message",
    name: "CEO Message",
    description:
      "Executive message or letter from leadership to the community.",
    defaultLayout: "classic-card",
    icon: MessageSquare,
    category: "Content & Text",
  },

  // People & Community
  {
    type: "team-members",
    name: "Team Members",
    description: "Showcase founders, team members, or organizers.",
    defaultLayout: "grid-profiles",
    icon: Users,
    category: "People & Community",
  },
  {
    type: "testimonials",
    name: "Testimonials",
    description: "Customer or member reviews and success stories.",
    defaultLayout: "carousel",
    icon: MessageSquare,
    category: "People & Community",
  },
  {
    type: "member-spotlight",
    name: "Member Spotlights",
    description:
      "Highlight featured community members with stories or profiles.",
    defaultLayout: "spotlight-cards",
    icon: UserCheck,
    category: "People & Community",
  },
  {
    type: "success-stories",
    name: "Success Stories",
    description: "Share real journeys and results achieved by the community.",
    defaultLayout: "story-cards",
    icon: Trophy,
    category: "People & Community",
  },
  {
    type: "chapters",
    name: "Chapters & Regions",
    description: "List local chapters, departments, or regional groups.",
    defaultLayout: "location-grid",
    icon: MapPin,
    category: "People & Community",
  },
  {
    type: "leaderboard",
    name: "Leaderboard",
    description: "Show top contributors, members, or community rankings.",
    defaultLayout: "rank-list",
    icon: Trophy,
    category: "People & Community",
  },
  {
    type: "latest-members",
    name: "Latest Members",
    description:
      "Display recently joined members with various presentation styles.",
    defaultLayout: "grid-cards",
    icon: UserCheck,
    category: "People & Community",
  },
  {
    type: "members-around-world",
    name: "Members Around the World",
    description:
      "Showcase global member distribution across countries and regions.",
    defaultLayout: "country-cards",
    icon: Map,
    category: "People & Community",
  },
  {
    type: "wall-of-fame",
    name: "Wall of Fame",
    description: "Honor and celebrate outstanding members and achievements.",
    defaultLayout: "podium",
    icon: Award,
    category: "People & Community",
  },

  // Business & Services
  {
    type: "communities",
    name: "Communities",
    description: "Showcase your communities, groups, or member organizations.",
    defaultLayout: "grid",
    icon: Users,
    category: "Business & Services",
  },
  {
    type: "marketplace",
    name: "Marketplace",
    description:
      "Display products, services, or offerings for sale or exchange.",
    defaultLayout: "grid",
    icon: Building,
    category: "Business & Services",
  },
  {
    type: "jobs",
    name: "Job Board",
    description: "List job openings, career opportunities, and positions.",
    defaultLayout: "list",
    icon: Briefcase,
    category: "Business & Services",
  },
  {
    type: "services",
    name: "Services",
    description: "Highlight services, offerings, or core features.",
    defaultLayout: "grid",
    icon: Briefcase,
    category: "Business & Services",
  },
  {
    type: "pricing",
    name: "Pricing Plans",
    description: "Membership or subscription pricing tiers.",
    defaultLayout: "pricing-cards",
    icon: CreditCard,
    category: "Business & Services",
  },
  {
    type: "partners",
    name: "Partners",
    description: "Showcase business partners, sponsors, and collaborators.",
    defaultLayout: "logo-row",
    icon: Handshake,
    category: "Business & Services",
  },
  {
    type: "logo-cloud",
    name: "Logo Showcase",
    description: "Display partner, sponsor, or member organization logos.",
    defaultLayout: "logo-grid",
    icon: Building,
    category: "Business & Services",
  },
  {
    type: "case-studies",
    name: "Case Studies",
    description: "In-depth stories showcasing results or community impact.",
    defaultLayout: "case-grid",
    icon: FileBarChart,
    category: "Business & Services",
  },
  {
    type: "benefits",
    name: "Membership Benefits",
    description: "Highlight perks and reasons to join the community.",
    defaultLayout: "benefit-icons",
    icon: Gift,
    category: "Business & Services",
  },

  // Marketing & Conversion
  {
    type: "cta-banner",
    name: "Call to Action",
    description: "Prominent action banner to drive signups or conversions.",
    defaultLayout: "centered-banner",
    icon: Megaphone,
    category: "Marketing & Conversion",
  },
  {
    type: "newsletter",
    name: "Newsletter Signup",
    description: "Email subscription and updates section.",
    defaultLayout: "inline-form",
    icon: Mail,
    category: "Marketing & Conversion",
  },
  {
    type: "social-proof",
    name: "Social Proof",
    description: "Customer reviews, ratings, and trust indicators.",
    defaultLayout: "inline-proof",
    icon: Shield,
    category: "Marketing & Conversion",
  },
  {
    type: "countdown-banner",
    name: "Countdown Banner",
    description: "Time-sensitive offers, event countdowns, and deadlines.",
    defaultLayout: "centered-countdown",
    icon: Timer,
    category: "Marketing & Conversion",
  },
  {
    type: "announcement",
    name: "Announcement",
    description: "Important updates, news, or promotional banners.",
    defaultLayout: "top-strip",
    icon: Bell,
    category: "Marketing & Conversion",
  },
  {
    type: "donation",
    name: "Donation Block",
    description: "Collect donations or contributions from supporters.",
    defaultLayout: "donation-simple",
    icon: Heart,
    category: "Marketing & Conversion",
  },
  {
    type: "announcement-bar",
    name: "Announcement Bar",
    description:
      "Top notification bar for alerts, promotions, and important messages.",
    defaultLayout: "info-message",
    icon: Bell,
    category: "Marketing & Conversion",
  },

  // Data & Analytics
  {
    type: "stats",
    name: "Stats & Metrics",
    description: "Display key numbers like members, events, or growth.",
    defaultLayout: "stats-row",
    icon: BarChart3,
    category: "Data & Analytics",
  },
  {
    type: "comparison-table",
    name: "Comparison Table",
    description: "Feature comparisons, pricing charts, and plan details.",
    defaultLayout: "table-grid",
    icon: Table,
    category: "Data & Analytics",
  },
  {
    type: "polls",
    name: "Interactive Polls",
    description: "Ask questions and collect community opinions.",
    defaultLayout: "poll-card",
    icon: BarChart,
    category: "Data & Analytics",
  },

  // Events & Timeline
  {
    type: "events",
    name: "Events",
    description: "Highlight upcoming or past community events.",
    defaultLayout: "event-cards",
    icon: Calendar,
    category: "Events & Timeline",
  },
  {
    type: "timeline",
    name: "Timeline",
    description: "Show community journey, milestones, or growth history.",
    defaultLayout: "vertical-timeline",
    icon: Clock,
    category: "Events & Timeline",
  },
  {
    type: "event-countdown",
    name: "Event Countdown",
    description: "Countdown timer for upcoming events or launches.",
    defaultLayout: "timer-large",
    icon: Timer,
    category: "Events & Timeline",
  },
  {
    type: "milestones",
    name: "Milestones",
    description: "Show progress over time with achievements or goals reached.",
    defaultLayout: "milestone-track",
    icon: Award,
    category: "Events & Timeline",
  },
  {
    type: "roadmap",
    name: "Roadmap",
    description: "Display upcoming features, goals, or planned updates.",
    defaultLayout: "horizontal-roadmap",
    icon: Route,
    category: "Events & Timeline",
  },

  // Media & Interactive
  {
    type: "media-gallery",
    name: "Media Gallery",
    description: "Image or video gallery showcasing community moments.",
    defaultLayout: "masonry-gallery",
    icon: Image,
    category: "Media & Interactive",
  },
  {
    type: "video-spotlight",
    name: "Video Spotlight",
    description:
      "Featured video content like demos, testimonials, or highlights.",
    defaultLayout: "centered-video",
    icon: Video,
    category: "Media & Interactive",
  },
  {
    type: "social-feed",
    name: "Social Media Feed",
    description: "Show recent posts from Instagram, Twitter, or LinkedIn.",
    defaultLayout: "feed-grid",
    icon: Share2,
    category: "Media & Interactive",
  },
  {
    type: "podcast",
    name: "Podcast Episodes",
    description: "List podcast episodes with audio players and descriptions.",
    defaultLayout: "episode-list",
    icon: Headphones,
    category: "Media & Interactive",
  },
  {
    type: "embed-block",
    name: "Embed Block",
    description:
      "Third-party content like videos, forms, or interactive widgets.",
    defaultLayout: "fullwidth-embed",
    icon: Code,
    category: "Media & Interactive",
  },

  // Learning & Development
  {
    type: "courses",
    name: "Courses",
    description:
      "Highlight available courses, curriculum, or training content.",
    defaultLayout: "course-cards",
    icon: GraduationCap,
    category: "Learning & Development",
  },
  {
    type: "research",
    name: "Research Highlights",
    description: "Showcase research, insights, whitepapers, or reports.",
    defaultLayout: "research-list",
    icon: FlaskConical,
    category: "Learning & Development",
  },

  // Structure & Navigation
  {
    type: "process-steps",
    name: "How It Works",
    description: "Explain steps or workflows in a simple flow.",
    defaultLayout: "step-timeline",
    icon: Route,
    category: "Structure & Navigation",
  },

  {
    type: "feature-highlights",
    name: "Feature Highlights",
    description: "Highlight key benefits or platform features.",
    defaultLayout: "icon-list",
    icon: Star,
    category: "Structure & Navigation",
  },
  {
    type: "sitemap",
    name: "Sitemap",
    description: "Organized navigation links and site structure overview.",
    defaultLayout: "link-columns",
    icon: Star,
    category: "Structure & Navigation",
  },

  // Contact & Location
  {
    type: "contact",
    name: "Contact Block",
    description: "Contact details, links, and inquiry options.",
    defaultLayout: "simple-contact",
    icon: Phone,
    category: "Contact & Location",
  },
  {
    type: "location-map",
    name: "Location Map",
    description: "Interactive maps showing offices, events, or service areas.",
    defaultLayout: "map-fullwidth",
    icon: Map,
    category: "Contact & Location",
  },

  // Recognition & Awards
  {
    type: "achievements",
    name: "Achievements",
    description: "Display awards, certifications, and milestone badges.",
    defaultLayout: "badge-grid",
    icon: Award,
    category: "Recognition & Awards",
  },

  // Compliance & Legal
  {
    type: "privacy-policy",
    name: "Privacy Policy",
    description: "Legal document describing how you handle user data.",
    defaultLayout: "simple-privacy",
    icon: Shield,
    category: "Compliance & Legal",
  },
  {
    type: "terms-conditions",
    name: "Terms & Conditions",
    description: "The legal agreement between you and your users.",
    defaultLayout: "simple-terms",
    icon: FileText,
    category: "Compliance & Legal",
  },
];

export const BASIC_MODULE_TYPES: ModuleType[] = [
  "custom-content",
  "faq",
  "blog",
  "team-members",
  "testimonials",
  "services",
  "pricing",
  "cta-banner",
  "newsletter",
  "stats",
  "events",
  "timeline",
  "media-gallery",
  "contact",
  "location-map",
  "privacy-policy",
  "terms-conditions",
];
