import {
  Globe,
  Calendar,
  Briefcase,
  Users,
  MessageSquare,
  ClipboardList,
  BarChart3,
  UserCheck,
  Award,
  Sparkles,
  ShoppingBag,
  Bell,
  Mail,
  Shield,
  type LucideIcon,
} from "lucide-react";

export const MODULE_ICONS: Record<string, LucideIcon> = {
  website: Globe,
  events: Calendar,
  jobs: Briefcase,
  communities: Users,
  forums: MessageSquare,
  surveys: ClipboardList,
  polls: BarChart3,
  members: UserCheck,
  mentorship: Award,
  gamification: Sparkles,
  marketplace: ShoppingBag,
  announcements: Bell,
  notifications: Bell,
  email: Mail,
};

export const MODULE_CATEGORY_LABELS: Record<string, string> = {
  website: "Web & Content",
  events: "Engagement",
  jobs: "Career & Growth",
  communities: "Community",
  forums: "Discussions",
  surveys: "Audience & Research",
  polls: "Interactions",
  members: "People & Directory",
  mentorship: "Advisory & Learning",
  gamification: "Rewards & Status",
  marketplace: "Commerce",
  announcements: "Broadcasts",
  notifications: "Delivery",
  email: "Campaigns",
};
